### ISSUE TITLE
h2 연동 및 테스트

### ISSUE THREAD

**Issue by hoya2222** [hoya2222/test-pettalk#4]

**Comment by hoya2222** [comment]
```
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
```
